function [fitresult, gof] = bestfit_getRvalue_BodePlot(freq, amp)
%CREATEFIT(FREQ,AMP_NOTDB)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : freq
%      Y Output: amp_notdB
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Feb-2018 11:33:48


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( freq, amp );
eq = 20*log10(1/sqrt(1+(2133/2133)^2));
% Set up fittype and options.
ft = fittype( '20*log10(1/sqrt(1+(x/a)^2))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.673885174488307;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
semilogx(xData, yData, 'ob', 'Linewidth',2);
hold on
h = plot(fitresult);
hold on 
% plot(8226,eq,'r*')
legend( h, 'Vout/Vin (dB) vs. Frequency', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel Frequency
ylabel Amplitute(dB)
grid on
grid minor



