function [fitresult, gof] = createCustomFit(R, F)
%CREATEFIT(R,F)
%  Create a fit.
%
%  Data for 'Polyfit' fit:
%      X Input : R
%      Y Output: F
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Feb-2018 20:39:53


%% Fit: 'Polyfit'.
[xData, yData] = prepareCurveData( R, F );

% Set up fittype and options.

ft = fittype( '2*(a*(x/13.629)^(2/-1.5862)+b*(x/13.629)^(1/-1.5862)+c)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.306082944538608 0.631262387563701 0.318740075730708];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Polyfit' );
h = plot( fitresult, xData, yData );
legend( h, 'F vs. R', 'Polyfit', 'Location', 'NorthEast' );
% Label axes
xlabel R
ylabel F
grid on


