function [fitresult, gof] = CreepFit_GeneralFxn_ABND(t_108g1, R_108g1)
%CREATEFIT3(T_108G1,R_108G1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t_108g1
%      Y Output: R_108g1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Feb-2018 20:07:41


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t_108g1, R_108g1 );

% Set up fittype and options.
ft = fittype( '(1-(a*x.^n))*exp(-b*(x.^n))*d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0];
opts.StartPoint = [0.86869470536351 0.0844358455109103 0.399782649098896 0.259870402850654];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.

h = plot( fitresult, xData, yData );
legend( h, 'R_108g1 vs. t_108g1', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel t_108g1
ylabel R_108g1
grid on


