%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Fangming/Documents/PUPD_Project/c term/Data/Creep Experiment/2018-1-28 Data_forMATLAB.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/01/31 20:28:01

%% Import the data
[~, ~, raw] = xlsread('/Users/Fangming/Documents/PUPD_Project/c term/Data/Creep Experiment/2018-1-28 Data_forMATLAB.xlsx','Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
% DataforMATLAB = table;

%% Allocate imported array to column variable names
Time_1N = data(:,1);
Data_1N = data(:,2);
Time_2N = data(:,3);
Data_2N = data(:,4);
Time_3N = data(:,5);
Data_3N = data(:,6);
Time_4N = data(:,7);
Data_4N = data(:,8);
Time_5N = data(:,9);
Data_5N = data(:,10);

%% Clear temporary variables
clearvars data raw R;