function [fitresult, gof] = createFit_R(t133_R, r133_R)
%CREATEFIT1(T133_R,R133_R)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : t133_R
%      Y Output: r133_R
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Dec-2017 00:34:26


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( t133_R, r133_R );

% Set up fittype and options.
ft = fittype( '(1-(a*x.^n))*exp(-b*(x.^n))*d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0];
opts.StartPoint = [0.048 2 0.489764395788231 0.186872604554379];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Curve Fit' );
h = plot( fitresult);
h.Color = [0.16 0.42 0.65];              % set line color to red
h.MarkerEdgeColor = [0 0 1];    % set marker color to blue
h.LineWidth = 3;
legend( h, 'r133_R vs. t133_R', 'untitled fit 2', 'Location', 'NorthEast' );

hold on
plot(xData, yData,'r','Linewidth',3);
% Label axes
xlabel t133_R
ylabel r133_R
grid on


