function [fitresult, gof] = createFit( t133_R_R0, r133_R_R0)
%CREATEFIT(T133G_RR0,R133G_RR0)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t133g_RR0
%      Y Output: r133g_RR0
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Dec-2017 20:08:16


%% Fit: 'Creep Fit'.


[xData, yData] = prepareCurveData( t133_R_R0, r133_R_R0 );

% Set up fittype and options.
ft = fittype( '(1-(a*x.^n))*exp(-b*(x.^n))',...
    'independent', 'x', 'dependent', 'y' );
% c = ((massInGram/1000)*9.8)/1.27e-4;

opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.StartPoint = [0.4 0.9 0.7];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Create Fit' );


h = plot( fitresult);
h.Color = [0.16 0.42 0.65];              % set line color to red
h.MarkerEdgeColor = [0 0 1];    % set marker color to blue
h.LineWidth = 2;
% legend( h, 'r133g_RR0 vs. t133g_RR0', 'untitled fit 1', 'Location', 'NorthEast' );
% ax = gca;
% ax.YLim = [0,0.2];
% ax.XLim = [0,3];
% Label axes

% hold on
% plot(xData, yData,'r','Linewidth',3);

xlabel Time(min)
ylabel R/R0
grid on
grid minor

